# Generated by Django 4.2.4 on 2023-09-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedPages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='id',
        ),
        migrations.AddField(
            model_name='feed',
            name='Feed_ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
