# Generated by Django 4.2.4 on 2023-09-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedPages', '0003_remove_feed_searchbar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table=None,
        ),
    ]
