# Generated by Django 4.2.4 on 2023-10-03 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedPages', '0005_feed_isdeleted'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feed',
            table='feedtable',
        ),
    ]
