# Generated by Django 4.2.4 on 2023-10-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedPages', '0006_alter_feed_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Feed_ID',
        ),
        migrations.AddField(
            model_name='feed',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
