# Generated by Django 4.2.4 on 2023-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedPages', '0007_remove_feed_feed_id_feed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='course',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
