# Generated by Django 4.2.4 on 2023-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedPages', '0008_alter_feed_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='course',
            field=models.IntegerField(max_length=255),
        ),
    ]
