# Generated by Django 4.2.4 on 2023-09-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='none', max_length=200)),
                ('Last_Name', models.CharField(default='none', max_length=200)),
                ('GPA', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('Major', models.TextField(default='Majorless')),
                ('email', models.TextField(default='null')),
                ('password', models.CharField(default='null', max_length=255)),
                ('PhoneNumber', models.DecimalField(decimal_places=0, default=0, max_digits=1000)),
            ],
        ),
    ]
