# Generated by Django 4.2.4 on 2023-09-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up_Pages', '0002_alter_userprofile_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='user',
        ),
    ]
