# Generated by Django 4.2.4 on 2023-09-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up_Pages', '0003_rename_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='sign_up_pages_db',
        ),
    ]
