# Generated by Django 4.2.4 on 2023-09-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up_Pages', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
