# Generated by Django 4.2.4 on 2023-09-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_Up_Pages', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
