# Generated by Django 4.2.4 on 2023-09-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='none', max_length=200)),
                ('password', models.CharField(default='null', max_length=255)),
            ],
        ),
    ]
