# Generated by Django 4.2.4 on 2023-09-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_In_Pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='Name',
            new_name='email',
        ),
    ]
