# Generated by Django 4.2.4 on 2023-09-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_In_Pages', '0002_rename_name_signin_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signIn',
            new_name='signInModel',
        ),
    ]
