# Generated by Django 4.2.4 on 2023-09-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_In_Pages', '0003_rename_signin_signinmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signInModel',
            new_name='user',
        ),
    ]
