# Generated by Django 4.2.4 on 2023-09-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_In_Pages', '0004_rename_signinmodel_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='sign_up_pages_user',
        ),
    ]
